### ISSUE TITLE
Generated Files

### ISSUE THREAD

**Issue by rindlespot** [0xD0GF00D/DocumentSASS#1]
Has anyone posted a zipped copy of the output files somewhere for those of us not on Linux?  I tried using the link to the google Colab, but it appears to be dead.

**Comment by 0xD0GF00D** [comment]
No idea why the link broke. Sorry for the trouble. Here is the content of the notebook, which one can easily run on Colab:

```
# Run to download code, compile, run code, then zip and download result.
!git clone https://github.com/0xD0GF00D/DocumentSASS.git
!make -C DocumentSASS
!zip DocumentSASS.zip DocumentSASS/*.txt

# The download may take a minute on Colab.
from google.colab import files
files.download("DocumentSASS.zip")
```
